### ISSUE TITLE
FOB erro

### ISSUE THREAD

**Issue by pcms01** [FlyAtlantic/acars#17]
A leitura do FOB apresentada está representada por kg quando devia ser por Lbs, o valor que acho que é recebido pelo acars do simulador é em Lbs e tem de se converter antes.
Isto também deve causar um erro depois nos outros pessos

**Comment by pedro2555** [comment]
Não deve ter nada que ver com as conversões de imperial para métrico. Segundo o que eu entendo de ler a tabela de offsets do FSUIPC, consegue-se obter a capacidade dos vários tanques, e a percentagem de combustível que têm.

Vou tentar explicar em exemplo para o tanque central, será repetir o processo para os restantes tanques e somar tudo para obter o FOB em peso.

Usando os seguintes offsets, assumindo que já têm as correcções indicadas na tabela:

- `0AF4` Fuel weight as pounds per gallon * 256

- `0B74` Fuel: centre tank level, % * 128 * 65536

- `0B78` Fuel: centre tank capacity: US Gallon

Podemos escrever os seguinte pseudocódigo:

```
if 0B78 > 0
   FOB = 0B78 * 0B74 // capacidade * nível
   FOB = FOB * 0AF4 // multiplicar pela taxa de conversão
   FOB = FOB * 3.7854118 // para converter de galões para kilos
```

Se repetirmos para os restantes tanques devemos ter indicação perfeita do nível de combustível.
